### ISSUE TITLE
Latest version no longer works

### ISSUE THREAD

**Issue by arichardson** [WolleTD/clang-format-checker#10]
I have been using this action in various projects but at some point in the past few months it has stopped working and gives an error message that doesn't make much sense to me (for example here https://github.com/CTSRD-CHERI/llvm-project/runs/5399922258?check_suite_focus=true):
```
/usr/bin/docker run --name wolletdclangformatlatest_6b30b0 --label 7db2d7 --workdir /github/workspace --rm -e INPUT_SOURCE-REF -e INPUT_TARGET-REF -e INPUT_CLANG-VERSION -e INPUT_FETCH-DEPTH -e FETCH_DEPTH -e CLANG_VERSION -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/llvm-project/llvm-project":"/github/workspace" wolletd/clang-format:latest  "dev" "f3071695d3cc[8](https://github.com/CTSRD-CHERI/llvm-project/runs/5399922258?check_suite_focus=true#step:6:8)f23670417bd91281d1fcf7a1c89"
From https://github.com/CTSRD-CHERI/llvm-project
 * branch                f30716[9](https://github.com/CTSRD-CHERI/llvm-project/runs/5399922258?check_suite_focus=true#step:6:9)5d3cc8f23670417bd91281d1fcf7a1c89 -> FETCH_HEAD
fatal: couldn't find remote ref refs/tags/f3071695d3cc8f23670417bd91281d1fcf7a1c89
```

I don't see anywhere in the script that would emit the `couldn't find remove ref` error message, only `die "fatal: couldn't find ref ${src}"`. I am also surprised that there is a refs/tags prefix.
The latest successful PR that I can find is `11 Nov 2021`, so it must be one of the commits after that. I wonder if the problem is that we are passing an explicit source ref that is just a SHA? `source-ref: "${{ github.event.pull_request.head.sha }}"` 

The github action definition is as follows:
```

name: Check coding style
on: [pull_request]
defaults:
  run:
    shell: bash
jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Try to fetch required commits
        run: |
          set -xe
          echo "base_ref=${{ github.base_ref }}"
          echo "github.event.pull_request.head.sha=${{ github.event.pull_request.head.sha }}"
          # Based on https://stackoverflow.com/questions/54181901/fetching-only-the-range-of-commits-not-present-in-base-branch
          for ((depth = 8; depth <= 65536; depth *= 2)); do
              echo "trying depth $depth ..."
              git fetch "--depth=$depth" origin "${{ github.base_ref }}:${{ github.base_ref }}"
              git fetch "--depth=$depth" origin "+${{ github.event.pull_request.head.sha }}"
              if git merge-base "${{ github.base_ref }}" "${{ github.event.pull_request.head.sha }}"; then
                  echo "found with depth=$depth"
                  break
              fi
          done
      - name: List commits
        run: git log --oneline "${{ github.base_ref }}..${{ github.event.pull_request.head.sha }}"
      - name: Run clang-format
        uses: wolletd/clang-format-checker@v1
        with:
          source-ref: "${{ github.event.pull_request.head.sha }}"
          target-ref: "${{ github.base_ref }}" # required, merge target
          clang-version: 12     # optional, default: 12
```

**Comment by WolleTD** [comment]
Thanks for your report (and usage of my Action :smile:). When I added the script for local usage, I had to make the internal script work with source-refs other than `HEAD` to not modify the working directory.
So, since https://github.com/WolleTD/clang-format-checker/commit/8125fdcc265d88e55c5a0e98f0965ecdcc914ed7, anything fed into `source-ref` in CI has to be able to be `rev-parse`d as `origin/{source-ref}` and either fetchable directly from `origin` or as a tag.
IIRC, those things are true for branches, tags and the `pull/##/merge`-ref in `github.event.pull_request.head.ref`. But not for a SHA, apparently. I missed testing those.
The `fatal: couldn't find remote ref` error is from the `git fetch origin tag $ref` command which is executed after the second `checkout origin/$ref` (with a SHA as ref) fails.

**Comment by arichardson** [comment]
Thank you very much for fixing this! @WolleTD would it be possible to update the v1 tag so we automatically get the new version? If not I could probably also use the commit hash instead.

**Comment by WolleTD** [comment]
I'm irritated that it doesn't work. The changes only affect the docker image and v1 should still pull `latest`, which should be the current master. But maybe there's a layer of caching inside GH Actions I don't know about.

I pushed the v1 tag, please try again.

**Comment by arichardson** [comment]
@WolleTD Sorry for the noise, it appears to be working again! https://github.com/CTSRD-CHERI/llvm-project/runs/5651536538?check_suite_focus=true shows all commits were checked and passed clang-format. Thanks for this extremely useful GitHub action 🙂
