### ISSUE TITLE
using custom clang-formt file in action

### ISSUE THREAD

**Issue by hpaegel** [WolleTD/clang-format-checker#19]
I like the action in general, but miss the feature to pass a custom `BasedOnStyle` value to clang-format through the yml-file. 

It would be sufficient/perfect if the use of a custom `.clang-format` file would be supported. Maybe it is, but haven't found it?

**Comment by WolleTD** [comment]
I noticed this myself a few weeks ago: at some point I changed the action to not checkout the source commit.
Creating the diffs works without it and it preserves the current working directory.

Now however, `clang-format` uses it's default configuration without a checkout before.
You could just run an `actions/checkout` before, but I don't like that, the action should be independent.

The action already has to check if a repository is present and should just checkout the source again if it's not.
Code around that is a little ugly and would get worse by just hacking it in. Still not much work, will try to do it on the weekend.

**Comment by hpaegel** [comment]
This solves my confusion on why my changes to the config-file had no affect.
With the checkout action manually included it now works how it should.

Not needing the separate action would be nicer but it still functions like this :)

**Comment by WolleTD** [comment]
Thinking about it, the script actually should use the `.clang-format` of each individual commit.
Suppose you:
1. push a branch with code changes: format check is fine
2. add another commit that changes `.clang-format`
3. push again: script uses new `.clang-format`, previously ok commits possibly fail now

I'd say that's wrong and every commit should have exactly one correct format, not depending on changes in other commits.

**Comment by WolleTD** [comment]
I haven't realized my own last comment, but the action should now work without `actions/checkout` before and use the `.clang-format` file of the source commit.
